### ISSUE TITLE
Should overall budget be dynamic?

### ISSUE THREAD

**Issue by regisphilibert** [project-cx/coreui-hugo#2]
![pasted image at 2018_01_22 07_59 pm](https://user-images.githubusercontent.com/1480503/35245880-b3dd59b2-ff92-11e7-976f-514263894484.png)

Header of the page displays the sum of people and budget of every projects.

It is easy to calculate the total head count of all projects from the People page because they are entered in the Front Matter of areas as integer.

But for the budget they are entered in the front matter as strings "500k" or "1.5M" making the overall calculation impossible.

How should we program the displaying of the global budget ?

- Dynamically: We will need to enter them in the front matter as integer (500000, or 15000000) then we should be able to display them in a friendlier way on the page using [lang.NumFmt](https://gohugo.io/functions/numfmt/). With this solution, the content manager doesn't control the format used to display budget on the project cards.
- Staticly: The information should be entered in the Front Matter of the people's section _index.md. With this solution content manager controls the format of the budget in the head of the page and on the cards.

Need direction. 

Cheers

**Comment by DinisCruz** [comment]
Yes that sounds great, let's do that

**Comment by DinisCruz** [comment]
The dynamic option

**Comment by regisphilibert** [comment]
Allright, sor for Budget, we'll sum the budget of every "area"
For the head count we'll sum the head_count of every "projects"
We could use "project" for summing budget but they don't have the info in their front matter, only "spent"

**Comment by regisphilibert** [comment]
I'm closing, b
